spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url:
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug