INSERT INTO product VALUES(1, '우리은행', '스무살 우리 정기적금', '상관없음', '회사원|프리랜서|전업주부|자영업|무직', '재테크', '상관없음', '상관없음', '상관없음', '상관없음', '19~34', '적금','청년','1년제|3.3%|월 20만원 이하', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/woori.jpg', '20대 버킷리스트 목돈 마련을 위해 GO!');
INSERT INTO product VALUES(2, '우리은행', '해외여행 한번 가보자! 적금', '상관없음', '회사원|프리랜서|전업주부|자영업|무직', '재테크', '상관없음', '상관없음', '상관없음', '상관없음', '35~60', '적금','여행','2년제|2.3%|월 100만원 이하', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/woori.jpg', '40대 해외여행 목돈 마련을 위해 GO!');
INSERT INTO product VALUES(3, '국민은행', '슬슬 모을 때가 됐다! 적금', '상관없음', '회사원|프리랜서|전업주부|자영업|무직', '재테크', '상관없음', '상관없음', '상관없음', '상관없음', '60~', '적금','노년','5년제|2.1%|월 120만원 이하', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kb.png', '노후 자금을 모으기 위한 적금입니다.');
INSERT INTO product VALUES(4, '하나은행', '예비신랑신부 적금', '상관없음', '회사원|프리랜서|전업주부|자영업|무직', '재테크', '상관없음', '상관없음', '상관없음', '상관없음', '19~34', '적금','청년|결혼','1년제|2.3%|월 150만원 이하', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/hana.png', '결혼 자금을 모으기 위한 적금입니다.');
INSERT INTO product VALUES(5, '하나은행', '오빠차 뽑았다 널 데리러 가는 적금', '상관없음', '회사원|프리랜서|전업주부|자영업|무직', '재테크', '상관없음', '상관없음', '상관없음', '상관없음', '19~34', '적금','청년|자동차','1년제|2.3%|월 100만원 이하', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/hana.png', '자동차를 마련하기 위한 적금입니다.');
INSERT INTO product VALUES(6, '국민은행', '내돈내산 집 마련 적금', '상관없음', '상관없음', '재테크', '자가', '상관없음', '1억 미만', '상관없음', '19~34', '적금','청년|결혼','3년제|2.6%|월 100만원 이하', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kb.png', '집을 마련하기 위한 적금입니다.');

INSERT INTO product VALUES(7, '하나은행', '청년 전세자금대출', '100000000', '상관없음', '상관없음', '전세|월세', '상관없음', '상관없음', '상관없음', '19~34', '대출','청년|전세|자금','2|100000000|2년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/hana.png', '청년을 위한 전세자금 대출입니다.');
INSERT INTO product VALUES(8, '우리은행', '직장인 생활비 대출', '5000000', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '대출','생활비|담보','4|5000000|1년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/woori.jpg', '직장인을 위한 생활자금 대출입니다.');
INSERT INTO product VALUES(9, '우리은행', '50년 집 담보 대출', '300000000', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '대출','생활비','4|300000000|50년','https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/woori.jpg', '고정 금리로 50년 길게 대출해드립니다!');
INSERT INTO product VALUES(10, '국민은행', '대학생을 위한 열공 학자금 대출!', '5000000', '학생', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '19~34', '대출','교육|열공|학자금','4|5000000|10년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kb.png', '열심히 공부하는 대학생들의 걱정을 덜어주는 학자금 대출입니다.');
INSERT INTO product VALUES(11, '카카오뱅크', '소중한 내 자동차 눈물 머금고 담보 대출', '30000000', '상관없음', '상관없음', '상관없음', '있음', '상관없음', '상관없음', '상관없음', '대출','자동차|드림카|담보','4|30000000|1년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kakaobank.png', '소중한 자동차를 맡기고 빌리는 대출입니다.');
INSERT INTO product VALUES(12, '케이뱅크', '대출 받기 어려운 분들을 위한 다 빌려줘 신용 대출!', '5000000', '프리랜서|무직', '관심사', '상관없음', '있음', '상관없음', '~2천만', '상관없음', '대출', '프리랜서|무직', '4|5000000|1년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kbank.jpg', '프리랜서, 무직과 같은 신용대출 받기 어려우신 분들을 위한 대출입니다.');

INSERT INTO product VALUES(13, '한국투자증권', '게임마니아 자산 펀드', '1000000', '프리랜서|무직', '상관없음', '상관없음', '있음', '상관없음', '상관없음', '상관없음', '펀드','게임|게임마니아|재테크','10|1000000|1년','https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/korea.png', '게임의 관심이 많으신 분들을 위한 게임관련 회사를 모아놓은 펀드입니다.');
INSERT INTO product VALUES(14, '신한금융투자', '유망 IT 성장주 투자 펀드!', '1000000', '프리랜서,무직', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '펀드','IT|코딩/개발|성장주|재테크','20|1000000|3년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/shinhan.png', '미래 발전 가능성이 있는 IT 성장주를 모아놓은 펀드입니다.');
INSERT INTO product VALUES(15, '토스증권', '레오나르도 다빈치 펀드!', '3000000', '프리랜서|무직', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '펀드','영상/사진|글쓰기|재테크|성장주','15|3000000|2년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/toss.png', '예술 관련주를 모아놓은 펀드입니다.');
INSERT INTO product VALUES(16, '신한금융투자', '노후를 부탁해!!', '100000000', '상관없음', '상관없음', '상관없음', '상관없음', '1억~10억|10억 이상', '상관없음', '60~', '펀드','재테크','12|100000000|1년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/shinhan.png', '은퇴한 분들을 위한 노후 자금 펀드입니다.');
INSERT INTO product VALUES(17, '토스증권', '코로나로 빛난 재테크 펀드!', '100000000', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '펀드','재테크|코로나','17|3000000|2년', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/toss.png', '코로나로 인해 수혜받을 수 있는 주식을 모아놓은 펀드입니다.');
INSERT INTO product VALUES(18, '한국투자증권', '매월 배당 받자,배당금 펀드!', '100000000', '상관없음', '상관없음', '상관없음', '상관없음', '10억 이상', '1억 이상', '상관없음', '펀드','재테크','5|100000000|1년','https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/korea.png', '배당금을 안정적으로 받을 수 있는 펀드입니다.');

INSERT INTO product VALUES(19, '신한은행', '신한카드 Developer Dream', '상관없음', '상관없음', '할인', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '카드','카드|코딩/개발|할인','해외겸용 1만원|전월 실적 30만원 이상|스타벅스50% 할인, 개발서적30% 할인, CGV10% 할인, 인프런강의10% 할인', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/shinhan.png', '개발자들을 위한 신용카드');
INSERT INTO product VALUES(20, 'IBK기업은행', 'IBK 소확행 카드', '상관없음', '상관없음', '할인,적립', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '카드','카드|재태크|할인 및 적립','해외겸용 1만원|전월 실적 30만원 이상|대중교통 건당 200원 할인, 간편결제 10% 할인, 대형마트10% 적립, 주유소 리터당 60원 할인, 온라인 쇼핑 7% 적립, 편의점 7%적립', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/IBK.png', '소소한 행복과 기쁨을 위한 알뜰한 재테크 카드');
INSERT INTO product VALUES(21, '국민은행', 'KB 문화 톡톡 카드', '상관없음', '상관없음', '할인', '상관없음', '상관없음', '상관없음', '상관없음', '19~34', '카드','카드|문화|영화|할인 및 적립','해외겸용 1만원|전월 실적 30만원 이상|연극/뮤지컬 5000원 할인, CGV20% 할인, 카페/베이커리/외식 10% 할인, 온라인 쇼핑 7% 할인, 놀이공원/테마파크 15% 할인', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kb.png', '문화생활 활동을 위한 카드');
INSERT INTO product VALUES(22, '삼성카드', '네이버페이 cap cap', '상관없음', '상관없음', '적립', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '카드','카드|코로나|글쓰기|적립','해외겸용 1만원|전월 실적 30만원 이상|네이버페이 간펼결제 10% 적립, 모든 가맹점 네이버페이 5% 적립', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/samsung.png', '네이버페이 할인 및 적립 카드');
INSERT INTO product VALUES(23, '카카오 페이', '카카오 아트 페이 카드', '상관없음', '상관없음', '할인', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '카드','카드|그림/디자인|운동|할인','해외겸용 1만원|전월 실적 30만원 이상|미용실 업종 10% 할인, 미술관/전시회 10% 할인, 올리브영 10% 할인, 미술용품 관련 20% 할인, 전국 헬스장 30일 무료 이용', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kakaopay.jpeg', '그림/디자인/뷰티 관련 혜택 카드');
INSERT INTO product VALUES(24, '하나은행', '하나은행 익스트림 액티비티 카드', '상관없음', '상관없음', '할인', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '카드','카드|영상/사진|게임|할인','해외겸용 1만원|전월 실적 30만원 이상|모든 게임기 관련 구매 10% 할인, 앱스토어 유료게임앱 구매시 5% 할인, 넷플릭스/왓차/디지니플러스 20% 할인', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/hana.png', '영상/사진 게임을 위한 혜택 카드');

INSERT INTO product VALUES(25, '네이버', '네이버페이', '상관없음', '상관없음', '영상/사진|영화', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '멤버십','멤버십|영화','5|모든 영화관 20% 할인|SILVER','https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/naverpay.png', '전국에 있는 모든 영화관에 20% 할인이 적용됩니다.');
INSERT INTO product VALUES(26, '카카오', '카카오페이', '상관없음', '상관없음', '코딩/개발|영상/사진', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '멤버십','멤버십|전자기기|노트북','4|전자기기 구매 시 15% 할인|GOLD', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kakaopay.jpeg', '하이마트, 전자랜드에서 전자기기를 구매하면 15% 할인이 적용됩니다.');
INSERT INTO product VALUES(27, 'KT', 'KT 멤버십', '상관없음', '상관없음', '운동|그림/디자인|글쓰기', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '멤버십','멤버십|예체능','15|운동기구, 미술도구, 문구류|VIP', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/kt.png', 'KT 예체능 고객을 위한 멤버십 혜택입니다!');
INSERT INTO product VALUES(28, 'SK', 'SK 멤버십', '상관없음', '상관없음', '코딩/개발|재테크', '상관없음', '상관없음', '상관없음', '상관없음', '상관없음', '멤버십','멤버십|개발자|재테크','10|전자제품, 재테크도서, 개발 강의, 제테크 강의|GOLD', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/sk.png', 'SK 개발자분들 중 재테크의 관심이 많은 분들을 위한 멤버십입니다.');
INSERT INTO product VALUES(29, 'LG유플러스', 'U+멤버십', '상관없음', '상관없음', '멤버십|문화|영화', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '멤버십','멤버십|문화|영화','15|영화, 미술관/전시회, 놀이공원/테마파크, 동물원|VIP', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/uplus.png', '나만의 U+ 멤버십 혜택');
INSERT INTO product VALUES(30, '배달의민족', '배달의민족 멤버십', '상관없음', '상관없음', '멤버십|코로나|재테크', '상관없음', '상관없음', '상관없음', '상관없음', '19~34|35~60', '멤버십','멤버십|코로나','10|음식점, 식음료/베이커리, 배달팁, 포인트|VIP', 'https://facam-miniproject-bucket.s3.ap-northeast-2.amazonaws.com/logo/baemin.png', '배달의민족 멤버십 혜택');